Update leaderboard.yml

diff --git a/.github/workflows/leaderboard.yml b/.github/workflows/leaderboard.yml
--- a/.github/workflows/leaderboard.yml
+++ b/.github/workflows/leaderboard.yml
@@ -32,10 +32,14 @@ jobs:
         run: |
           git config --global user.name "bot"
           git config --global user.email "bot@github.com"
-          git add leaderboard.csv
+
+          echo "Checking leaderboard.csv content:"
+          cat leaderboard.csv || echo "File not found
+
+          git add -A
 
           if git diff --cached --quiet; then
-            echo "No changes to commit"
+            echo "No changes to commit
           else
             git commit -m "update leaderboard"
             git pull origin test-branch --rebase
